# SPDX-License-Identifier: Apache-2.0

name: Conftest

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conftest:
    name: Conftest Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Conftest
        uses: sentenz/actions/conftest@1.1.4
        with:
          policy-path: "./tests/policy"
