---
name: Continuous Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: continuous-release
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
      - name: Setup Release
        run: |
          make setup-continuous-release
      - name: Run Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make run-continuous-release
