# SPDX-License-Identifier: Apache-2.0

name: Regal

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  regal:
    name: Regal Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Run Regal
        uses: sentenz/actions/regal@1.1.4
        with:
          path: "./tests/policy"
          regal-version: "latest"
